# Script mode: cmake -DOUT=<file.cpp> -DINPUTS=<a.json;b.json;...> -P EmbedStyles.cmake
# Writes a translation unit defining tg::factoryStyleSources() with each JSON file as a raw
# string literal, so factory styles need no runtime file I/O (04, 07 §2).
set(body "")
set(count 0)
foreach(f IN LISTS INPUTS)
    file(READ "${f}" content)
    string(FIND "${content}" ")tgjson\"" bad)
    if(NOT bad EQUAL -1)
        message(FATAL_ERROR "${f} contains the raw-string delimiter )tgjson\"")
    endif()
    get_filename_component(name "${f}" NAME)
    string(APPEND body "    {\"${name}\", R\"tgjson(${content})tgjson\"},\n")
    math(EXPR count "${count} + 1")
endforeach()
if(count EQUAL 0)
    message(FATAL_ERROR "EmbedStyles: no input files")
endif()
set(src "// Generated by core/cmake/EmbedStyles.cmake from styles/*.json. Do not edit.
#include \"transitgen/StyleLoader.h\"

namespace tg {

namespace {
const EmbeddedStyle kFactoryStyles[] = {
${body}};
} // namespace

const EmbeddedStyle* factoryStyleSources(int& count) noexcept
{
    count = ${count};
    return kFactoryStyles;
}

} // namespace tg
")
# Only touch the output when it changes, so dependants are not rebuilt needlessly.
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
    if(old STREQUAL src)
        return()
    endif()
endif()
file(WRITE "${OUT}" "${src}")
